#! /usr/bin/perl

use warnings;
use strict;
use Text::CSV;
use Catmandu::Importer::MARC::ALEPHSEQ;
use Catmandu::Exporter::MARC::ALEPHSEQ;
use Catmandu::Fix::Inline::marc_map qw(:all);
use Catmandu::Fix::marc_add as => 'marc_add';


my @prefixarchiv = (
    'Alters- und Fürsorgekasse der Arbeiter und Arbeiterinnen der Bell AG',
    'Anleihen: Sammlung von Emissionsprospekten und Zeitungsausschnitten',
    'Anstalt für Arbeitsvermittlung',
    'Arbeitslosenkasse des Arbeiterbundes Basel',
    'Arbeitslosigkeit in der Basler Seidenbandindustrie, Hilfskomitee bzw. Hilfskommission für die Arbeitslosen der Textilindustrie',
    'Arbeitslosigkeit in der Stadt Basel',
    'Ausstellung "Arbeit der Frau" in der Basler Mustermesse',
    'Internationale Ausstellung für Binnenschiffahrt und Wasserkraftnutzung',
    'Schweizerische Ausstellung für Landwirtschaft, Forstwirtschaft und Fischerei (VI. Schweiz. landwirtschaftliche Ausstellung)',
    'Ausstellung "Land- und Ferienhaus" in der Basler Mustermesse',
    'Bauarbeiterstreik 1905, Initiativ-Komitee zur Unterstützung der Familien der ausgesperrten Bau-Arbeiter',
    'Arbeiter- bzw. Streikbewegung in der Basler Bandindustrie im Winter 1868/69',
    'IMABA, Internationale Briefmarken-Ausstellung 1948',
    'Donau-Gruppe der International Studies Conference',
    'Expertenkommission über Sparmassnahmen im Betrieb der kantonalen Anstalten des Kantons Zürich',
    'Exportforschungsinstitut in Basel (Projekt)',
    'Fürsorgekasse der Seidenbandindustrie',
    'Gesellschaft zu St. Margarethen',
    'Gewerbs-Innung Klein-Laufenburg (Bachgenossenschaft)',
    'Goldwäscher-Familienkasse',
    'Komitee für die Auslandschweizertage der Schweizer Mustermesse',
    'Internationale Kommission des Völkerbundes zur wirtschaftlichen und finanziellen Wiederaufrichtung Österreichs',
    'Kommission für Wirtschaftsfragen des Kantons Basel-Stadt',
    'Krankenlade der Zimmergesellen Basel',
    'Kranken-Unterstützungs-Verein Murg',
    'Kranken- und Sterbekasse der Möbelfabrik Zehnle & Bussinger',
    'Krippe zu St. Alban',
    'Krippe zu St. Leonhard',
    'Lukas-Stiftung der GGG',
    'Schweiz. Referendumskomitee gegen das Bundesgesetz über die Kranken- und Unfallversicherung (1911)',
    'Rheinschiffahrtskammer beider Basel',
    'Sarasin, Krankenkasse W. Sarasin & Co.',
    'Schülertuch-Stiftung der GGG',
    'Schuhmacher-Krankenkasse Basel',
    'Schweizer Rheinschiffahrts-Konvention',
    'Schweizerische Bibliographie für Statistik und Volkswirtschaft (SBSV)',
    'Schweizerische Statistische Gesellschaft, Ausstellung zu ihrer Geschichte',
    'Stiftung Kommission zur Suppenanstalt',
    'Familie Streckeisen-Caesar und Verwandte',
    'Surinam-Stiftung der Gesellschaft zur Beförderung des Guten und Gemeinnützigen',
    'Unterstützungskasse der Feuerwehr des Kantons Basel-Stadt bei Todesfällen',
    'Schweizerische Wohnungsausstellung in der Basler Mustermesse 1930',
    'Fritz-Mangold-Stiftung',
    'Stiftung zur Förderung des Schweizerischen Wirtschaftsarchivs (StSWA)',
    'Schweizerisches Wirtschaftsarchiv',
);

my @prefixfirmenarchiv = (
    'Aktienbrauerei zum Sternenberg, vorm. Gebr. Zeller',
    'A.G. zur Ausbeutung der Patente Mavrogordato',
    'Aktiengesellschaft zur Erstellung billiger Wohnungen',
    'Aktienverein Gerber',
    'J.S. Alioth & Cie.',
    'Appretur & Mechanische Werkstätten vorm. Aug. Vögelin AG',
    'Asiatische Pflanzungs- und Handels-Aktiengesellschaft',
    'Astra, Einkaufsgenossenschaft des Schweizerischen Schuhmacher-Meister-Verbandes',
    'Bachofen, Johann Jakob & Sohn, Seidenbandfabrikation',
    'Basler Bandfabrik vormals Trüdinger & Cons.',
    'Basler Bankierverein',
    'Bank in Basel AG',
    'Banque Suisse et Française',
    'Baugenossenschaft Basel',
    'Bau- und Industriekeramik AG',
    'Nicolaus de Hieronymus Bernoulli & Sohn, Drogerie und Materialwarenhandlung',
    'Bernoulli-Baer, Leonhard de Niklaus, Drogist und Materialwarenhändler',
    'Bernoulli-von der Tann, Willhelm de Leonhard, Kaufmann',
    'Bernoulli, Leonhard de Niklaus (Sohn) und Niklaus de Johann Bernoulli (Vater), Materialwarenhändler bzw. Apotheker',
    'Leonhard Bernoulli, Drogerie und Materialwaren',
    'Bischoff zu St. Alban',
    'Brenner, Emanuel & Cie, Papiermühle',
    'Basler Brodfabrik AG',
    'Bruckner AG, Weisswaren',
    'Caisse d\'Epargne du district de Moutier SA',
    'Basler Brauerei Cardinal',
    'Brauerei zum Warteck AG, vormals B. Füglistaller',
    'Chemische Union AG',
    'Färberei- u Appretur-Gesellschaft, vorm. Alexander Clavel & Fritz Lindenmeyer AG',
    'Basler Cliché-Fabrik AG',
    'Schweiz. Colonisations-Gesellschaft Santa Fé AG',
    'Compagnie des Eaux de Skutari et Kadi-Keui à Bâle',
    'Allgemeiner Consumverein Basel',
    'Allgemeine Creditbank AG',
    'Basler Credit-Gesellschaft',
    'Dampfschiffahrt-Gesellschaft \'Die Adler des Oberrheins\'',
    'Hans Balthasar Burckhardt und Sohn',
    'Dietschy, Faesch & Co., Weine und Spirituosen',
    'Drahtseilbahn Interlaken-Heimwehfluh AG',
    'Basler Drogerie Leonhard Bernoulli & Co., Kommandit-Aktiengesellschaft',
    'Baslerische Droschkenanstalt',
    'Ehinger-Stierlin, Otto, Manufakturwaren en gros',
    'Ei AG, Geflügel- und Eierfarm',
    'Zinstragende Ersparniskasse, Basel',
    'Faesch, Isaak und Hoffmann, Johann Jakob, holländische Handelsagenten auf Curacao',
    'Feller AG',
    'Aktiengesellschaft Florettspinnerei Ringwald AG',
    'Frères Merian',
    'Frey, Thurneysen & Christ, Seidenbandfabrik',
    'Fürstenberger-Passavant Hans-Georg, Wollhandlung',
    'Genossenschaft für Häute- und Fellverwertung Basel',
    'Genossenschaft Schweizerischer Gipsermeister',
    'Gerberei Brombach AG',
    'Gesellschaft für Bandfabrikation AG',
    'Goldene Apotheke BS, GABA',
    'Gougguer, Xavier & Comp., Baumwoll- & Leinenweberei',
    'Gruner AG, Ingenieurunternehmung',
    'Haag-Kraus, Leonhard, Partikular, alt Schmiedemeister',
    'Basler Handelsbank',
    'Handwerker-Bank Basel AG',
    'Hausbrandzentrale, Kohlenverkaufsstelle für Hausbrand und Kleinbetriebe',
    'Stöckli-Fuhrer, Jean, Fahrradteile und Geflechtfabrik',
    'Hypothekenbank in Basel AG',
    'Immobilien-Genossenschaft Basel',
    'Schweizerische Import-Trust AG (SITAG)',
    'Schappe SA',
    'Hotel Jura, Basel',
    'Kaffeehalle zu Schmieden',
    'Keller, Autotransport & Garage AG',
    'Keller-Paravicini, Johann Jakob, Eisenhandlung',
    'Keller-Vonkilch, Johann Jakob, Bierbrauerei und Weinhandlung',
    'Kling, Camille, Bank- und Effektengeschäft',
    'Knoblauch, Emil & August, Kartonfabrik',
    'Koechlin & Söhne, Bandfabrikanten',
    'Schweizerische Kohlen-Genossenschaft',
    'Kohlenkontor Vulcana AG',
    'Kohlenzentrale AG',
    'Buchdruckerei Kohlhepp AG',
    'Schweizerische Konkordatsbanken',
    'Konsumverein Birsfelden',
    'Konsumverein Bremgarten und Umgebung',
    'Kumpf-Krebs, Bettwaren',
    'Leihkasse für den Bezirk Rheinfelden',
    'Lierow, Albert, Druckerei-Lithographie',
    'Linder, Johann Jakob & Cie, Seidenbandfabrikation',
    'Löffel, Wilhelm, Baugeschäft',
    'Basler Löwenbräu AG',
    'Meili-Wahl, August, Alteisenhandel, Fabrikation von Lötfett und -zinn',
    'Meyer, Johann & Sohn, Manufakturwaren',
    'Müller & Hess, Baugeschäft',
    'Edwin Naef, Seidenwarenfabrikations-Geschäft',
    'Nova Margarine- und Speisefettfabriken AG',
    'Oel- & Fettverwertungs AG',
    'Paravicini-Burckhardt, Leonhard, Eisen- und Metallwarenhandlung',
    'Paravicini, Emanuel, Eisengiesserei',
    'Passavant & Cie, Bankgeschäft',
    'Passavant, Gebrüder Johann Ulrich & Leonhard, Seidenzeug-Fabrikation und -Handel',
    'Perrollaz [Gebrüder Jean, Francois und Joseph] und Konsorten, Tuch- und Kurzwarenhandlung',
    'Basler Personenschiffahrtsgesellschaft (Genossenschaft)',
    'Basler Pfandleihanstalt AG',
    'Neue Birstaler Portland-Cement-Fabrik AG',
    'Dietrich Preiswerk & Comp, Seidenbandfabrikation',
    'Ragus AG',
    'Rebsamen & Naegely, Farben und Lacke',
    'Respinger & Co., Drogerie und Materialwaren',
    'Ateliers Reymond Frères & Cie S.A.',
    'Rheinhafen AG',
    'Ryff & Co. AG, Strickwarenfabrik',
    'Salubratapeten-Fabrik',
    'Sarasin & Cie I, Seidenbandfabrikation',
    'Sarasin & Cie II, Bandfabrik',
    'Sarasin Söhne AG, Seidenwarenfabrikation',
    'Schappecordonnetspinnerei St. Jakob AG',
    'Aktien-Gesellschaft Schappe- und Cordonnet-Spinnerei Ryhiner',
    'Schieferwerk Gantenbach',
    'Schlumberger-Zuber, Charles, Drogenhandel en gros und Schlumberger-Ehinger, Amedée',
    'Schmid und Cie, Leinenweberei',
    'Schweighauserische Buchdruckerei',
    'Schweizerische Reederei und Neptun AG',
    'Service de Bateaux à vapeur entre Bâle et Strasbourg, Renouard de Bussierre, Oswald Frères & Comp.',
    'Simonius, Vischer & Co.',
    'Société Immmobilière d\'Algérie SA (Charles Zahn-Sarasin)',
    'Basler Sparkasse',
    'Spar- und Leihkasse Bremgarten AG',
    'Internationale Speditions-Gesellschaft Schneider & Cie. AG',
    'von Speyr & Cie, Bank- und Speditionsgeschäft',
    'Spinnerei Atzenbach',
    'C. Detloff’s Buchhandlung',
    'Steuer & Cie., Tuchgrosshandel',
    'Stoecklin & Co., Papierfabrik',
    'Suter und Suter AG, Architekten',
    'Texas Landgesellschaft in Basel',
    'Thurneysen & Cie, Seidenbandfabrik',
    'Trottet, Edouard, Mercerie & Quincaillerie en gros',
    'Trust Chimique SA, Produits chimiques et pharmaceutiques',
    'Veillard: Gustav Veillard & Cie. AG, Bank-, Geldwechsel- und Effektengeschäft',
    'Vischer, Leonhard & Sohn, Kolonial- und Farbwarenhandlung',
    'Volderauer, Simon & Comp, Spezerei- und Eisenhandlung',
    'Volkstuch AG',
    'Firmen von Martin Metzger: Importagentur Martin Metzger, Velorex AG, LASERon AG',
    'Waeffler & Co, AG, Handel in Baumwollgarnen und Zwirnen',
    'Wagner, Franz & Cie., Indienne-Druckerei',
    'Walz & Eschle, Seifenfabrik',
    'Warenhaus Loeb',
    'Basler Waschanstalt AG',
    'Schweizerische Wechsel- & Effektenbank AG',
    'Wolle & Seide AG',
    'Würgler & Cie, Zigarrenfabrik',
    'Weis-Leissler, Markus und Nachfolger (Württembergerhof)',
    'Forcart-Weis & Söhne (Württembergerhof)',
    'Burckhardt-Wildt & Sohn (Württembergerhof)',
    'Forcart-Weis und Burckhardt-Wildt (Württembergerhof)',
    'Burckhardt & Co, Seidenbandfabrikation (Württembergerhof)',
    'Zahn & Cie, Bankgeschäft',
    'Zentral-Waschanstalt AG',
    'Zimmerlin, Forcart & Cie, Florettseiden-Spinnerei',
    'Ingenium AG',
    'G. Kiefer & Cie. AG',
    'Heberlein & Co. AG',
    'Hofstetter AG Möbelwerkstätten',
    'Württembergerhof',
    'Alusuisse',
    'Dr. Peter Schürch, Seeland Apotheke (Biel)',
    'Rumpf\'sche Kreppweberei AG (Immobiliengesellschaft Weidengasse 49 AG ab 1959)',
    'Hero'
);

my @prefixpersonenarchiv = (
    'Wengen-Meyenrock, Fanny Rosalie à, Witwe, Rentière',
    'Bauer, Stephan, Prof. Dr. jur.',
    'Bernoulli-Burckhardt, Niklaus de Johann, Materialwarenhändler und Apotheker',
    'Bernoulli-Baer, Elisabeth',
    'Bernoulli, Johann de Leonhard, Partikular',
    'Beugger, Johann Alexander',
    'Bischoff-Buxtorf, Johannes, Bandfabrikant',
    'Bon, Primus, Wirt, Pächter des Bahnhofrestaurants Zürich-Hauptbahnhof',
    'Bopp, Johann Jakob, Müller',
    'Brüderlin-Rächer, Karl, Wirt',
    'Bührer, Gebrüder',
    'Bullinger-Usteri, Balthasar Gottfried, Friedensrichter und Bertha Schulthess-Bullinger',
    'Burckhardt-Bischoff, Adolf, Dr. h.c., Wirtschaftspolitiker und Bankier',
    'Burckhardt-Burckhardt, Rudolf, Dr. med.',
    'Burckhardt-Forcart, Daniel und Ludwig',
    'Burckhardt-Iselin, Rosine',
    'Burckhardt-Keller, Johann Jakob, Deputat',
    'Burckhardt-Merian, Julius, Kaufmann',
    'Burckhardt-Sarasin, Carl, Dr. h.c., Seidenbandfabrikant',
    'Burckhardt-Vischer, Carl Felix Wilhelm, Bankier',
    'Burckhardt-Vischer, Karl, Rentier',
    'Burckhardt-Vischer, Sophie',
    'Burckhardt-Wildt, Daniel, Bandfabrikant',
    'Buri, Laurenz, Julius und Emil, Marchand-Tailleurs',
    'Burkhard-Wuhrmann Werner, Delegierter der Zolltarif-Kommission',
    'Christen, Erwin, Ingenieur',
    'Christen, Jakob, Ingenieur',
    'Egli, Johann Jakob, Tailleur',
    'Eglinger, Joh. Jakob',
    'Sarasin-Iselin, Alfred, Dr. h.c., Bankier',
    'Escher, Johannes und Escher-Landolt, Anna Barbara',
    'Faesch, Joh. Rudolf, Bürgermeister von Basel',
    'Faesch-Vinet, Johannes von Johannes, Rentner, Privatbankier',
    'Falckner-Birr, Emanuel, Bürgermeister der Stadt Basel',
    'Finckenstein, Dr. Hans Wolfram, Graf von, Vermala sur Sierre',
    'Forcart-Merian, Dietrich, Seidenbandfabrikant',
    'Forcart-Merian, Carl Wilhelm (-von Speyr)',
    'Friedmann, Fritz, Leiter der Reklame-Centrale der Rheinbrücke, Publizist',
    'Frischmann, Daniel, Geschäftsmann',
    'Geering-Schliephacke, Hermine',
    'Geering, Traugott (1859-1932)',
    'Gérault, H., Paris, Fournisseur des Principales Maisons de Banque, Chemin de Fer, Administration et Commerce',
    'Gerber, Adolphe Louis, Strohhutfabrikant',
    'Geigy-Merian, Johann Rudolf, Farbwaren- und Drogenfabrikant',
    'Goetzen-Sarasin, Anna von, Landwirtin',
    'Grimm, Johann Karl, Ratsherr und Bürgermeister',
    'Gubler, Robert, Dr. med, Bezirksarzt',
    'Künzel-Kressler, Jakob, Architekt, Basel',
    'Heuberger-Stoll, Emil, Wagnermeister',
    'Hildenbrand, Vinzenz Jakob',
    'Hoffmann, Emanuel, Seidenbandfabrikant',
    'Hoffmann, Goenner & Cie, Tuchgeschäft',
    'Hörler-Krug, Anna Maria, Partikularin',
    'Huber-Rohner, Johann Jakob, Prof. der Astronomie',
    'Iffenthaler-Mohler, Ludwig, Kanzleisekretär',
    'Iselin-Weis (Falkner), Daniel',
    'Jenny-Rosenmund, Oskar Hugo, Dr. phil. Kantonsstatistiker',
    'Wolf, Benjamin (vormals Wolff, Felix) und Wolf, Bernhard',
    'Keller-Göttisheim, Marie, Ehefrau des Franz Hermann Keller-Göttisheim, Dr. med, Kurarzt in Rheinfelden',
    'Kern-His, Eduard, Dr. jur., Notar',
    'Kinkelin, Hermann, Prof. Dr., Mathematiker und Politiker',
    'König, Magdalena, Damenschneiderin und Putzmacherin und Zimmermann-König, Johannes, Handelsmann',
    'Krug, Johannes (1795-1866)',
    'Landmann, Julius, Prof. Dr. phil., Nationalökonom',
    'LeGrand-Heusler, Johannes und Familie',
    'Lendorff-Berri, Karl, Architekt',
    'Linder, Johann Jakob, Mannenschneider',
    'Linder-Preiswerk, Hans',
    'Lutz, Johannes, Wirt zum Engel',
    'Maeglin, Benoît',
    'Mangold-Müller, Friedrich, Regierungsrat, Prof. für Statistik, Vorsitzender SWA',
    'Margreth-Geering, Elisabeth',
    'Menzi, Elsa, Laborantin',
    'Merian-Burckhardt, Sophia',
    'Merian-Burckhardt, Christoph',
    'Merian-Hoffmann, Christoph',
    'Merian-Werthemann, Susanne',
    'Meyer, Diethelm, Pfarrer und Dekan',
    'Meyer, Emanuel Walter, Partikular',
    'Mez, John Richard, Prof. der Nationalökonomie',
    'Moerikofer-Widmer, Peter Paul, Kaufmann, stv. Börsenkommissar',
    'Moppert-Burckhardt, Esther',
    'Oeschy, Joseph',
    'Pack-Mosis, Jakob Christoph, Steinmetzmeister und Zimmermann',
    'Paganini, Robert, Dr. Chemiker, Treuhänder',
    'Poeppig, Eduard Friedrich',
    'Portmann, Melchior, Müllermeister, Klingentalmühle',
    'Preiswerk-Forcart, Lucas, Bandfabrikant',
    'Raecher, Friedrich',
    'Rahm-Waser, Emil, Dr. med.',
    'Rosenlächer-Gubelmann, Joseph, Glockengiesser',
    'Ryhiner-Christ, Emanuel, Rentier',
    'Sarasin-Forcart, Esther Emilie (1807-1866)',
    'Sarasin, Johann von Johann Lukas / Burckhardt-Brek, Elie, J.U.D.',
    'Schmidlin-Von der Mühll, Wilhelm, Baumeister',
    'Schneider, Salome, Dr. phil, Privat-Dozentin und Bibliothekarin',
    'Schönauer-Bernoulli, Daniel, Handelsmann',
    'Scholtz, Caspar (1594-1615) und Jacob (1596-?)',
    'Seiz, Wilhelm, Secrétaire-inspecteur de la Société suisse des chefs d\'atelier décorateurs',
    'Haag, Friedrich, Schmiedemeister und Siegrist, Emil, Wagnermeister',
    'Simonius-Blumer, Alfons (Vater), Cellulosefabrikant Simonius-Vischer, Paul (Sohn), Dipl. Ing. ETH,',
    'Speiser-Sarasin, Paul, Prof. Dr. jur.',
    'Speiser-Strohl, William, Direktor der Eisenbahnbank',
    'Stähelin-Passavant, Hieronymus, Eisenhändler',
    'Straumann-Gamper, Friedrich Heinrich, Spenglermeister',
    'Streckeisen-Schaub, Mathias',
    'Streckeisen-Caesar, Emanuel, Kaufmann und Bankier',
    'Stünzi (Familie), Käpfnach bei Horgen',
    'Sulger-Staehelin, Andreas und Marie, Direktor Schweizerische Centralbahn',
    'Taur, Friedrich, Herausgeber und Redaktor der Schweizerischen Eisenbahn- und Handelszeitung',
    'Familie Vischer-Burckhardt, Peter, Bandfabrikant',
    'Vischer-Preiswerk, Sophia',
    'Weber-Weber, Adolf, Ingenieur',
    'Weiss, Frank, Dr., Vorsteher der Ausgleichskasse Basel',
    'Forcart-Iselin, Achilles (1777-1884)',
    'Wyss, Ulrich, Gemeindeschreiber',
    'Ziegler, Bernhartin, Haus zum Löwenkopf',
    'Stalder-Spiess, W.H., Bankdirektor',
    'Egli, Gustav, Dr., Generalsekretär Landesverband Freier Schweizer Arbeiter',
    'Leuthold, Laurance',
    'Fellmann-Keller, Paul',
    'Tietz, Bruno, Prof. Dr.',
    'Bombach, Gottfried, Prof. Dr. (1919-2010)',
);

my @prefixteilarchiv = (
    'Bürgerspital Basel',
    'Forstverwaltung der Bürgergemeinde Basel',
    'Gesellschaft zur Beförderung des Guten und Gemeinnützigen (GGG)',
    'Knie, Gebrüder, Schweizer National-Zirkus',
    'Psychiatrische Universitätsklinik Friedmatt',
    'Standard Telephon und Radio AG (STR)',
    'Zwilchenbart AG, Auswanderungs- und Passageagentur, Reisebureau',
);

my @prefixverbandsarchiv = (
    'Basler Vereinigung zur Förderung des Luftverkehrs (BVFL)',
    'Basler Bandfabrikanten-Verein',
    'Bandpropaganda-Comité des Basler Bandfabrikanten-Vereins',
    'Banksektion des Basler Handels- und Industrievereins',
    'Bildhauerverein Basel',
    'Bruderschaft der Schuhmacher in Basel',
    'Schweizerischer Coiffeurmeister-Verband',
    'Basler Gartenbau-Gesellschaft',
    'Genossenschaft der Seidenbandweber von Baselland und Umgebung',
    'Genossenschaft zur Förderung des Schweizerisch-Ungarischen Warenverkehrs, GESUWA',
    'Gesellschaft des katholischen Vereinshauses \'Basler Hof\'',
    'Basler Gesellschaft für Seidenindustrie',
    'Schweizerische Gesellschaft für Statistik und Volkswirtschaft',
    'Statistisch-Volkswirtschaftliche Gesellschaft Basel',
    'Gewerkschaft der Erd- und Tiefbauarbeiter, Sektion des Arbeiterbundes Basel',
    'Schweizerischer Grossisten-Verband',
    'Handels- und Industrie-Verein in Basel',
    'Brennstoffhändler-Verband der Nordwestschweiz',
    'Importvereinigung der Engros-Firmen der Mercerie, Bonneterie- und Kurzwaren-Branchen (I.M.B.)',
    'Interessenverband Schweizerischer Grossisten',
    'Schweizerisches Komitee für Chemie',
    'Schweizerisches Komitee für Weltwirtschaft (SKW)',
    'Internationaler Metallarbeiterbund IMB, Fédération internationale des ouvriers sur métaux',
    'Sammlerschutzstelle des Verbandes Schweizerischer Philatelisten-Vereine',
    'Posamenter-Verband Baselland (alter Verband)',
    'Schmiede- und Wagner-Fachverein von Basel und Umgebung',
    'Schuhmachermeister-Verein Basel',
    'Schweizerischer Arbeiter-Verein',
    'Schweizerische Vereinigung für Dokumentation (SVD)',
    'Schweizerischer Seidenbandfabrikanten-Verein',
    'Staatsarbeiter-Verein Basel',
    'Schweizerischer Strassenbahner-Verband, Sektion Basel',
    'Syndikat der schweizerischen Bandfabrikanten',
    'Verband der Angestellten und Arbeiter des Kantons Basel-Stadt',
    'Verband der Arbeiter und Arbeitgeber der Basler Bandfabriken (VAB)',
    'Verband Basler Detaillisten',
    'Verband Basler Goldschmiede',
    'Verband oberrheinischer Bandfabrikanten (VOB)',
    'Verband Schweizerischer Drahtgeflecht-Fabrikanten',
    'Verband schweizerischer Roskopfuhren-Industrieller',
    'Verband Schweizerischer Transit- und Welthandelsfirmen',
    'Schweizerischer Verband für Wohnungswesen und Wohnungsreform',
    'Verband Schweizerischer Dampf- und Motorwäschereien',
    'Verein der Arbeiter des Gas-, Wasser- und Elektrizitätswerks Basel',
    'Verein der Basler Staatsangestellten',
    'Verein der Basler Strassenbahner',
    'Verein für Hauspflege in der Münster- und St. Elisabethengemeinde Basel',
    'Verein für Mässigkeit und Volkswohl',
    'Vereinigung der Walzstahlverarbeiter, Schweizerische',
    'Internationale Vereinigung für gesetzlichen Arbeiterschutz',
    'Basler Vereinigung für industrielle Landwirtschaft und Innenkolonisation',
    'Vereinigung zur Anstrebung einer Gotthardbahn',
    'Schweizerische Vereinigung zur Förderung des internationalen Arbeiterschutzes, Sektion Basel',
    'Basler Volkswirtschaftsbund',
    'Vereinigung Basler Ökonomen',
    'Verband Schweizerischer Zollangestellter (Sektion Basel)',
    'Schweizerischer Laborpersonalverband (SLV)',
);

die "Argumente: $0 Input Output \n" unless @ARGV == 2;

my($inputfile,$outputfile) = @ARGV;
my $tempfile = './temp.seq';

open my $in, "<", $inputfile or die "$0: open $inputfile: $!";
open my $out, ">", $outputfile or die "$0: open $outputfile: $!";

my $f008pos6;

NEWLINE: while (<$in>) {
    my $sysnumber = (substr $_ , 0, 9);
    my $line = $_;
    my $field = (substr $line, 10, 3);
    my $ind1 = (substr $line, 13, 1);
    my $ind2 = (substr $line, 14, 1);
    my $content = (substr $line, 18);
    chomp $line;
    chomp $content;

    my @subfields = split(/\$\$/, $line);
    shift @subfields;

    # Wir gehen hier davon aus, dass Feld 008 immer vor Feld 593 vorkommt - sonst haben wir ein Problem

    if ($field =~ /490/) {
        foreach (@prefixarchiv) {
            if ($line =~ /\$\$a\Q$_\E/) {
                $line =~ s/\$\$a\Q$_\E/\$\$aArchiv $_/g;
                print $out $line . "\n";
            }
        }
        foreach (@prefixteilarchiv) {
            if ($line =~ /\$\$a\Q$_\E/) {
                $line =~ s/\$\$a\Q$_\E/\$\$aTeilachiv $_/g;
                print $out $line . "\n";
            }
        }
        foreach (@prefixpersonenarchiv) {
            if ($line =~ /\$\$a\Q$_\E/) {
                $line =~ s/\$\$a\Q$_\E/\$\$aPersonenarchiv $_/g;
                print $out $line . "\n";
            }
        }
        foreach (@prefixfirmenarchiv) {
            if ($line =~ /\$\$a\Q$_\E/) {
                $line =~ s/\$\$a\Q$_\E/\$\$aFirmenarchiv $_/g;
                print $out $line . "\n";
            }
        }
        foreach (@prefixverbandsarchiv) {
            if ($line =~ /\$\$a\Q$_\E/) {
                $line =~ s/\$\$a\Q$_\E/\$\$aVerbandsarchiv $_/g;
                print $out $line . "\n";
            }
        }

    }

}

exit;

